version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.10.8-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action-server:
    container_name: actions
    image: sarahlevins/levinschatbots:actionserver1
    env_file: .env
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055" 